### ISSUE TITLE
Non-interactive markers 

### ISSUE THREAD

**Issue by DVassilev** [lelandrichardson/react-native-maps#416]
Is it possible to set markers to not be interactive and be just like an object "painted" onto the map so that they don't register any click events and it is as if you're interacting with the map if you try click on them?

**Comment by xvalentino** [comment]
@DVassilev in a way I'd like to do this. What I'd like is to overwrite the default on click function of the markers. Right now it animates to the marker in the center, and I'd like to animate the marker to the bottom of screen. I'm having some problems trying to do that smoothly since it seems I can't turn off the default action.

**Comment by julienvincent** [comment]
+1 would also like to override.

**Comment by DVassilev** [comment]
I found a way to make the marker not respond to any events by doing the following:

`<Marker pointerEvents="none" ...otherProps>`
