### ISSUE TITLE
Support for live track user location and update self marker?

### ISSUE THREAD

**Issue by ahmed1490** [lelandrichardson/react-native-maps#53]
https://github.com/facebook/react-native/commit/3d0ff69e40f0262e0ffc6f6023ec958b52eeb986

**Comment by lelandrichardson** [comment]
cc @christopherdro who is working on this i think

**Comment by christopherdro** [comment]
@lelandrichardson We decided not to support this because of the behavioral differences between iOS and Android. Setting `followUserLocation` would cause the map to keep snapping back if you decided to pan out. I believe this was specific to iOS.

The better solution would be to just update the `region` prop `<Mapview />`. With this approach, we should be able to make use of `<MapView.Animated />` and animate the region changes.

I haven't had a change to test this out yet, but I do plan on looking into it some more and will report back here with any new findings.

**Comment by christopherdro** [comment]
Here is the link to the conversation @lelandrichardson and I had on this feature.
https://gitter.im/lelandrichardson/react-native-maps?at=56a26e05c54bc2bf180b7853
