### ISSUE TITLE
Map isn't updating on region prop change

### ISSUE THREAD

**Issue by elaygl** [lelandrichardson/react-native-maps#67]
I've been trying to run the sample you gave in the readme but couldn't make it work.

```
getInitialState() {
  return {
    region: {
                longitudeDelta: 18.162189759314053,
                latitudeDelta: 16.288021267949482,
                longitude: 53.07996740564704,
                latitude: 55.27790853263076
            }
  };
}

onRegionChange(region) {
  this.setState({ region });
}

render() {
  return (
    <MapView 
      region={this.state.region}
      onRegionChange={this.onRegionChange}
    />
  );
}
```

The map isn't changing according to the region in the state.

I debugged the Android project and noticed that the setRegion method not gets called.

I'm running with RN: 0.19.0

**Comment by jshaw22** [comment]
Where are you calling setRegion in your code? 

Try putting this in your onRegionChange: 

```
onRegionChange(region) {
     this.state.region.setValue(region); // not an object 
}
```

**Comment by elaygl** [comment]
The problem occurred because of the upgrade to RM 0.19.
They changed some imports in the native modules.

After updating the react-native-maps module to latest, problem is gone.

**Comment by Dzale** [comment]
I have the same issue on Android. onRegionChange function is called, component render() function is also called but the map doesn't load new data.  First image is my initial map, and second one is what happens when i zoom it few times. Did anyone have this problem or has idea how to fix it ?
Thanks!!

[
![image](https://cloud.githubusercontent.com/assets/9077950/14771370/463e8fd4-0a89-11e6-9fed-10d1fe6d5490.png)
](url)

[
![image](https://cloud.githubusercontent.com/assets/9077950/14771360/e760f4e8-0a88-11e6-9a0d-ac874c8bd719.png)
](url)
