### ISSUE TITLE
Animated.Region is not a function

### ISSUE THREAD

**Issue by ahmed1490** [lelandrichardson/react-native-maps#74]
There seems to be an error on my end when i try to run this. Can you please tell me what must be wrong here.

<img width="277" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/12875001/cf3d6fc0-cde0-11e5-85af-f711cb2f81e5.png">

<img width="296" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/12875005/ed3b6806-cde0-11e5-8f7c-3eade6c93237.png">

[Update] my mistake.. I didnt replace the file AnimatedImplementation.js
any update on when will this patch no longer needed. I am thinking of doing a presentation/workshop at my workplace on react native with this library as one of the example. This looks a weird fix to ask everyone to do.

**Comment by lelandrichardson** [comment]
@ahmed1490 the patch is only needed if you want to use the animated versions of the component. The rest of the component's API will work perfectly.

The real problem is that the `AnimatedWithChildren` class is not exported in react native. I will likely propose a new API to extend/create arbitrary animated classes soon, but this needs to be done in such a way that does not conflict with efforts to make the Animated API serializable and run on native threads.

**Comment by KarthickRaja3018** [comment]
Is that possible to enable default zoom control in react-native-maps or not ?
